allow-lan: false
mode: rule
tun:
  enable: true
  stack: mixed
  auto-detect-interface: true
proxies:
  - name: game
    type: socks5
    server: 127.0.0.1
    port: 16780
    udp: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - game
dns:
  enable: false
  nameserver:
    - https://223.5.5.5/dns-query
rules:
  - PROCESS-NAME,SpeedNet.exe,DIRECT
  - PROCESS-NAME,sniproxy.exe,DIRECT
  - PROCESS-NAME,StarRail.exe,PROXY
  - PROCESS-NAME,launcher.exe,PROXY
  - PROCESS-NAME,hpatchz.exe,PROXY
  - PROCESS-NAME,QtWebEngineProcess.exe,PROXY
  - PROCESS-NAME,ZFGameBrowser.exe,PROXY
  - PROCESS-NAME,crashreport.exe,PROXY
  - MATCH,DIRECT
